Repository jason-orginization-5257/prtest1, pull requests merged in 2022-02, with the labels that each got.

#1 first pull request
  file2.txt
Labels: bug

#2 Feat/issue 0001
  .idea/modules.xml
  .idea/prtest1.iml
  zzzz
Labels: good first issue

#4 feat/issue #3번에 대한 수정건입니다.
  zzzz
Labels: good first issue

#7 pr:이슈 수정하였습니다.
  file1.txt
Labels: bug, good first issue, fix

#10 issue 6번 수정했습니다
  zzzz
Labels: bug, fix

#11 리뷰 거부건으로 테스트합니다.
  zzzz
Labels: bug, good first issue, fix
